### PR TITLE
987902 no service deploy

### PR DESCRIPTION
**Pull request by RaphaelAudet**

### CODE REVIEW

**Review by Lilith-mx — COMMENTED** [review]
LGTM a few comments though
- on the README.md, wouldn't it be to refer to creating the alchemy service for the documentation or is it out of our scope?
-in usage.md, it could be more clear to say that the label of the service credentials should match...

**Comment by RaphaelAudet** [comment]
@mendix/digital_ecosystems updated the docs, please review

**Review by carlos-salinas — APPROVED** [review]
LGTM - I understood that we removed the Alchemy service from the automatic deployment, because in IBM Bluemix only one instance of this service can be at a given time in the organisation.

**Comment by RaphaelAudet** [comment]
yes, only one Alchemy can be free and afaik Standards Alchemy offer is not available for trial users.

To allow a maximum of people to deploy the sample, we decided to not deploy alchemy in the sample automatically

**Pull request merged**
