### PR TITLE
Speech to Text functionality

### PR DESCRIPTION
**Pull request by simo101**
Adding support for speech to text functionality.

### CODE REVIEW

**Comment by RaphaelAudet** [comment]
Hi @simo101 thanks for the pull-request, we appreciate the help. We'll look into it

**Comment by simo101** [comment]
@RaphaelAudet You're welcome.

**Comment by simo101** [comment]
Anyone had chance to take a look at this?

**Review by LilithZ — APPROVED** [review]
LGTM
Sorry for the bit of delay in the review Simon ;-) 
From now on though, we are going to make a Mendix based project and if you are planning to open a pull request please do it there so that we can also see and review the changes that you add to the modeler easier.
and hopefully then we are also faster with reviewing...

**Pull request merged**
